In [47]:
z = np.zeros(10)
z[1:]
np.where(z >= 0.0, 1, -1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
w = [2,3,4]
np.dot(X,w) + [0]

array([20, 47])

In [33]:
X = np.array([[1,2,3],[4,5,6]])
y = [1,0]

for xi, t in zip(X,y):
    print (xi, t)

[1 2 3] 1
[4 5 6] 0


In [27]:
import perceptron